zlanguage: android
dist: trusty
env:
  global:
  - ANDROID_TARGET=android-29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.2
  - FIREBASE_PROJECT_ID==medjournal
android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - "$ANDROID_TARGET"
  - android-28
before_script:
- wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-269.0.0-linux-x86.tar.gz
- tar zxf google-cloud-sdk-269.0.0-linux-x86.tar.gz google-cloud-sdk
- echo n | ./google-cloud-sdk/install.sh
- echo y | ./google-cloud-sdk/bin/gcloud components update
- echo y | ./google-cloud-sdk/bin/gcloud components install beta
- source google-cloud-sdk/path.bash.inc
- gcloud auth activate-service-account --key-file firebase.json
- gcloud config set project $FIREBASE_PROJECT_ID
script:
- chmod +x gradlew
- "./gradlew assembleDebug"
- "./gradlew assembleDebugAndroidTest"
- echo y | gcloud firebase test android run --app app/build/outputs/apk/debug/app-debug.apk
  --type=robo --device model=walleye,version=28,locale=en,orientation=portrait
before_install:
- openssl aes-256-cbc -K $encrypted_41abf659cb69_key -iv $encrypted_41abf659cb69_iv
  -in firebase.json.enc -out firebase.json -d
